export enum ActionType {
    // UI Actions
    UI_SET_THEME = 'UI_SET_THEME',
    UI_TOGGLE_SIDEBAR = 'UI_TOGGLE_SIDEBAR',
    UI_SET_ACTIVE_VIEW = 'UI_SET_ACTIVE_VIEW',
    UI_SET_LOADING = 'UI_SET_LOADING',
    UI_SET_ERROR = 'UI_SET_ERROR',
    UI_CLEAR_ERROR = 'UI_CLEAR_ERROR',
    
    // Chat Actions
    CHAT_SET_MESSAGES = 'CHAT_SET_MESSAGES',
    CHAT_ADD_MESSAGE = 'CHAT_ADD_MESSAGE',
    CHAT_CLEAR_MESSAGES = 'CHAT_CLEAR_MESSAGES',
    CHAT_SET_ACTIVE_SESSION = 'CHAT_SET_ACTIVE_SESSION',
    CHAT_CREATE_SESSION = 'CHAT_CREATE_SESSION',
    CHAT_DELETE_SESSION = 'CHAT_DELETE_SESSION',
    CHAT_SET_INPUT_TEXT = 'CHAT_SET_INPUT_TEXT',
    CHAT_SET_PROCESSING = 'CHAT_SET_PROCESSING',
    
    // Settings Actions
    SETTINGS_SET_MODEL = 'SETTINGS_SET_MODEL',
    SETTINGS_SET_TEMPERATURE = 'SETTINGS_SET_TEMPERATURE',
    SETTINGS_SET_MAX_TOKENS = 'SETTINGS_SET_MAX_TOKENS',
    SETTINGS_SET_TELEMETRY_ENABLED = 'SETTINGS_SET_TELEMETRY_ENABLED',
    SETTINGS_SET_REQUIRE_CONFIRMATION = 'SETTINGS_SET_REQUIRE_CONFIRMATION',
    SETTINGS_SET_API_KEY = 'SETTINGS_SET_API_KEY',
    
    // Terminal Actions
    TERMINAL_EXECUTE_COMMAND = 'TERMINAL_EXECUTE_COMMAND',
    TERMINAL_SET_OUTPUT = 'TERMINAL_SET_OUTPUT',
    TERMINAL_CLEAR_OUTPUT = 'TERMINAL_CLEAR_OUTPUT',
    
    // Code Editor Actions
    EDITOR_SET_ACTIVE_FILE = 'EDITOR_SET_ACTIVE_FILE',
    EDITOR_UPDATE_CONTENT = 'EDITOR_UPDATE_CONTENT',
    EDITOR_SET_SELECTION = 'EDITOR_SET_SELECTION',
    
    // AI Actions
    AI_START_COMPLETION = 'AI_START_COMPLETION',
    AI_RECEIVE_COMPLETION = 'AI_RECEIVE_COMPLETION',
    AI_COMPLETION_ERROR = 'AI_COMPLETION_ERROR',
    AI_SET_STREAMING = 'AI_SET_STREAMING',
    
    // Auth Actions
    AUTH_LOGIN = 'AUTH_LOGIN',
    AUTH_LOGOUT = 'AUTH_LOGOUT',
    AUTH_SET_API_KEY = 'AUTH_SET_API_KEY',
    
    // Session Actions
    SESSION_INITIALIZE = 'SESSION_INITIALIZE',
    SESSION_RESET = 'SESSION_RESET'
} 